//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLEXEDC.WEB.UI.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="ServiceReference2.HDKQuerySR")]
    public interface HDKQuerySR {
        
        // CODEGEN: Generating message contract since the operation QueryServiceRequest is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:QueryServiceRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestResponse QueryServiceRequest(PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:QueryServiceRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestResponse> QueryServiceRequestAsync(PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class QueryServiceRequest_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sRNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SRNumber {
            get {
                return this.sRNumberField;
            }
            set {
                this.sRNumberField = value;
                this.RaisePropertyChanged("SRNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class QueryServiceRequest_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string sRStatusField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SRStatus {
            get {
                return this.sRStatusField;
            }
            set {
                this.sRStatusField = value;
                this.RaisePropertyChanged("SRStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryServiceRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequest_Input QueryServiceRequest_Input;
        
        public QueryServiceRequestRequest() {
        }
        
        public QueryServiceRequestRequest(PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequest_Input QueryServiceRequest_Input) {
            this.QueryServiceRequest_Input = QueryServiceRequest_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryServiceRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequest_Output QueryServiceRequest_Output;
        
        public QueryServiceRequestResponse() {
        }
        
        public QueryServiceRequestResponse(PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequest_Output QueryServiceRequest_Output) {
            this.QueryServiceRequest_Output = QueryServiceRequest_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HDKQuerySRChannel : PLEXEDC.WEB.UI.ServiceReference2.HDKQuerySR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HDKQuerySRClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.UI.ServiceReference2.HDKQuerySR>, PLEXEDC.WEB.UI.ServiceReference2.HDKQuerySR {
        
        public HDKQuerySRClient() {
        }
        
        public HDKQuerySRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HDKQuerySRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HDKQuerySRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HDKQuerySRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestResponse PLEXEDC.WEB.UI.ServiceReference2.HDKQuerySR.QueryServiceRequest(PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestRequest request) {
            return base.Channel.QueryServiceRequest(request);
        }
        
        public PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequest_Output QueryServiceRequest(PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequest_Input QueryServiceRequest_Input) {
            PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestRequest inValue = new PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestRequest();
            inValue.QueryServiceRequest_Input = QueryServiceRequest_Input;
            PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestResponse retVal = ((PLEXEDC.WEB.UI.ServiceReference2.HDKQuerySR)(this)).QueryServiceRequest(inValue);
            return retVal.QueryServiceRequest_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestResponse> PLEXEDC.WEB.UI.ServiceReference2.HDKQuerySR.QueryServiceRequestAsync(PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestRequest request) {
            return base.Channel.QueryServiceRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestResponse> QueryServiceRequestAsync(PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequest_Input QueryServiceRequest_Input) {
            PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestRequest inValue = new PLEXEDC.WEB.UI.ServiceReference2.QueryServiceRequestRequest();
            inValue.QueryServiceRequest_Input = QueryServiceRequest_Input;
            return ((PLEXEDC.WEB.UI.ServiceReference2.HDKQuerySR)(this)).QueryServiceRequestAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="ServiceReference2.HDKCreateSR")]
    public interface HDKCreateSR {
        
        // CODEGEN: Generating message contract since the operation CreateServiceRequest_1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:CreateServiceRequest_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Response CreateServiceRequest_1(PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:CreateServiceRequest_1", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Response> CreateServiceRequest_1Async(PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class CreateServiceRequest_1_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sRTypeField;
        
        private string summaryField;
        
        private string channelField;
        
        private string mDAField;
        
        private string subAreaField;
        
        private string nationalIdField;
        
        private string areaField;
        
        private string businessIdField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SRType {
            get {
                return this.sRTypeField;
            }
            set {
                this.sRTypeField = value;
                this.RaisePropertyChanged("SRType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("Summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
                this.RaisePropertyChanged("Channel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MDA {
            get {
                return this.mDAField;
            }
            set {
                this.mDAField = value;
                this.RaisePropertyChanged("MDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SubArea {
            get {
                return this.subAreaField;
            }
            set {
                this.subAreaField = value;
                this.RaisePropertyChanged("SubArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NationalId {
            get {
                return this.nationalIdField;
            }
            set {
                this.nationalIdField = value;
                this.RaisePropertyChanged("NationalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BusinessId {
            get {
                return this.businessIdField;
            }
            set {
                this.businessIdField = value;
                this.RaisePropertyChanged("BusinessId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class CreateServiceRequest_1_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string serviceRequestIdField;
        
        private string serviceRequestNumberField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServiceRequestId {
            get {
                return this.serviceRequestIdField;
            }
            set {
                this.serviceRequestIdField = value;
                this.RaisePropertyChanged("ServiceRequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceRequestNumber {
            get {
                return this.serviceRequestNumberField;
            }
            set {
                this.serviceRequestNumberField = value;
                this.RaisePropertyChanged("ServiceRequestNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateServiceRequest_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1_Input CreateServiceRequest_1_Input;
        
        public CreateServiceRequest_1Request() {
        }
        
        public CreateServiceRequest_1Request(PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1_Input CreateServiceRequest_1_Input) {
            this.CreateServiceRequest_1_Input = CreateServiceRequest_1_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateServiceRequest_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1_Output CreateServiceRequest_1_Output;
        
        public CreateServiceRequest_1Response() {
        }
        
        public CreateServiceRequest_1Response(PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1_Output CreateServiceRequest_1_Output) {
            this.CreateServiceRequest_1_Output = CreateServiceRequest_1_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HDKCreateSRChannel : PLEXEDC.WEB.UI.ServiceReference2.HDKCreateSR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HDKCreateSRClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.UI.ServiceReference2.HDKCreateSR>, PLEXEDC.WEB.UI.ServiceReference2.HDKCreateSR {
        
        public HDKCreateSRClient() {
        }
        
        public HDKCreateSRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HDKCreateSRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HDKCreateSRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HDKCreateSRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Response PLEXEDC.WEB.UI.ServiceReference2.HDKCreateSR.CreateServiceRequest_1(PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Request request) {
            return base.Channel.CreateServiceRequest_1(request);
        }
        
        public PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1_Output CreateServiceRequest_1(PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1_Input CreateServiceRequest_1_Input) {
            PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Request inValue = new PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Request();
            inValue.CreateServiceRequest_1_Input = CreateServiceRequest_1_Input;
            PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Response retVal = ((PLEXEDC.WEB.UI.ServiceReference2.HDKCreateSR)(this)).CreateServiceRequest_1(inValue);
            return retVal.CreateServiceRequest_1_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Response> PLEXEDC.WEB.UI.ServiceReference2.HDKCreateSR.CreateServiceRequest_1Async(PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Request request) {
            return base.Channel.CreateServiceRequest_1Async(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Response> CreateServiceRequest_1Async(PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1_Input CreateServiceRequest_1_Input) {
            PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Request inValue = new PLEXEDC.WEB.UI.ServiceReference2.CreateServiceRequest_1Request();
            inValue.CreateServiceRequest_1_Input = CreateServiceRequest_1_Input;
            return ((PLEXEDC.WEB.UI.ServiceReference2.HDKCreateSR)(this)).CreateServiceRequest_1Async(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="ServiceReference2.HDKUpdateSR")]
    public interface HDKUpdateSR {
        
        // CODEGEN: Generating message contract since the operation UpdateServiceRequest_1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:UpdateServiceRequest_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Response UpdateServiceRequest_1(PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:UpdateServiceRequest_1", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Response> UpdateServiceRequest_1Async(PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class UpdateServiceRequest_1_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string summaryField;
        
        private string closureCommentsField;
        
        private string serviceRequestStatusField;
        
        private string serviceRequestNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("Summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClosureComments {
            get {
                return this.closureCommentsField;
            }
            set {
                this.closureCommentsField = value;
                this.RaisePropertyChanged("ClosureComments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServiceRequestStatus {
            get {
                return this.serviceRequestStatusField;
            }
            set {
                this.serviceRequestStatusField = value;
                this.RaisePropertyChanged("ServiceRequestStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceRequestNumber {
            get {
                return this.serviceRequestNumberField;
            }
            set {
                this.serviceRequestNumberField = value;
                this.RaisePropertyChanged("ServiceRequestNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class UpdateServiceRequest_1_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateServiceRequest_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1_Input UpdateServiceRequest_1_Input;
        
        public UpdateServiceRequest_1Request() {
        }
        
        public UpdateServiceRequest_1Request(PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1_Input UpdateServiceRequest_1_Input) {
            this.UpdateServiceRequest_1_Input = UpdateServiceRequest_1_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateServiceRequest_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1_Output UpdateServiceRequest_1_Output;
        
        public UpdateServiceRequest_1Response() {
        }
        
        public UpdateServiceRequest_1Response(PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1_Output UpdateServiceRequest_1_Output) {
            this.UpdateServiceRequest_1_Output = UpdateServiceRequest_1_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HDKUpdateSRChannel : PLEXEDC.WEB.UI.ServiceReference2.HDKUpdateSR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HDKUpdateSRClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.UI.ServiceReference2.HDKUpdateSR>, PLEXEDC.WEB.UI.ServiceReference2.HDKUpdateSR {
        
        public HDKUpdateSRClient() {
        }
        
        public HDKUpdateSRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HDKUpdateSRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HDKUpdateSRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HDKUpdateSRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Response PLEXEDC.WEB.UI.ServiceReference2.HDKUpdateSR.UpdateServiceRequest_1(PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Request request) {
            return base.Channel.UpdateServiceRequest_1(request);
        }
        
        public PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1_Output UpdateServiceRequest_1(PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1_Input UpdateServiceRequest_1_Input) {
            PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Request inValue = new PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Request();
            inValue.UpdateServiceRequest_1_Input = UpdateServiceRequest_1_Input;
            PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Response retVal = ((PLEXEDC.WEB.UI.ServiceReference2.HDKUpdateSR)(this)).UpdateServiceRequest_1(inValue);
            return retVal.UpdateServiceRequest_1_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Response> PLEXEDC.WEB.UI.ServiceReference2.HDKUpdateSR.UpdateServiceRequest_1Async(PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Request request) {
            return base.Channel.UpdateServiceRequest_1Async(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Response> UpdateServiceRequest_1Async(PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1_Input UpdateServiceRequest_1_Input) {
            PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Request inValue = new PLEXEDC.WEB.UI.ServiceReference2.UpdateServiceRequest_1Request();
            inValue.UpdateServiceRequest_1_Input = UpdateServiceRequest_1_Input;
            return ((PLEXEDC.WEB.UI.ServiceReference2.HDKUpdateSR)(this)).UpdateServiceRequest_1Async(inValue);
        }
    }
}
