//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLEXEDC.WEB.UI.SiebelReferenceRequestGet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReferenceRequestGet.EDC_spcGet_spcContact_spcSR_spcWF")]
    public interface EDC_spcGet_spcContact_spcSR_spcWF {
        
        // CODEGEN: Generating message contract since the operation EDC_spcGet_spcSR_spcList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:EDC_spcGet_spcSR_spcList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListResponse EDC_spcGet_spcSR_spcList(PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:EDC_spcGet_spcSR_spcList", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListResponse> EDC_spcGet_spcSR_spcListAsync(PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class EDC_spcGet_spcSR_spcList_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/HDK%20Service%20Request")]
    public partial class ServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sRNumberField;
        
        private string typeField;
        
        private string areaField;
        
        private string subAreaField;
        
        private string statusField;
        
        private string subStatusField;
        
        private string priorityField;
        
        private string summaryField;
        
        private string closureCommentsField;
        
        private string citizenIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SRNumber {
            get {
                return this.sRNumberField;
            }
            set {
                this.sRNumberField = value;
                this.RaisePropertyChanged("SRNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SubArea {
            get {
                return this.subAreaField;
            }
            set {
                this.subAreaField = value;
                this.RaisePropertyChanged("SubArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SubStatus {
            get {
                return this.subStatusField;
            }
            set {
                this.subStatusField = value;
                this.RaisePropertyChanged("SubStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("Summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ClosureComments {
            get {
                return this.closureCommentsField;
            }
            set {
                this.closureCommentsField = value;
                this.RaisePropertyChanged("ClosureComments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CitizenId {
            get {
                return this.citizenIdField;
            }
            set {
                this.citizenIdField = value;
                this.RaisePropertyChanged("CitizenId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class EDC_spcGet_spcSR_spcList_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceRequest[] listOf_ServiceRequestField;
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/HDK%20Service%20Request", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceRequest[] ListOf_ServiceRequest {
            get {
                return this.listOf_ServiceRequestField;
            }
            set {
                this.listOf_ServiceRequestField = value;
                this.RaisePropertyChanged("ListOf_ServiceRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EDC_spcGet_spcSR_spcListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcList_Input EDC_spcGet_spcSR_spcList_Input;
        
        public EDC_spcGet_spcSR_spcListRequest() {
        }
        
        public EDC_spcGet_spcSR_spcListRequest(PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcList_Input EDC_spcGet_spcSR_spcList_Input) {
            this.EDC_spcGet_spcSR_spcList_Input = EDC_spcGet_spcSR_spcList_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EDC_spcGet_spcSR_spcListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcList_Output EDC_spcGet_spcSR_spcList_Output;
        
        public EDC_spcGet_spcSR_spcListResponse() {
        }
        
        public EDC_spcGet_spcSR_spcListResponse(PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcList_Output EDC_spcGet_spcSR_spcList_Output) {
            this.EDC_spcGet_spcSR_spcList_Output = EDC_spcGet_spcSR_spcList_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EDC_spcGet_spcContact_spcSR_spcWFChannel : PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcContact_spcSR_spcWF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDC_spcGet_spcContact_spcSR_spcWFClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcContact_spcSR_spcWF>, PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcContact_spcSR_spcWF {
        
        public EDC_spcGet_spcContact_spcSR_spcWFClient() {
        }
        
        public EDC_spcGet_spcContact_spcSR_spcWFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDC_spcGet_spcContact_spcSR_spcWFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcGet_spcContact_spcSR_spcWFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcGet_spcContact_spcSR_spcWFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListResponse PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcContact_spcSR_spcWF.EDC_spcGet_spcSR_spcList(PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListRequest request) {
            return base.Channel.EDC_spcGet_spcSR_spcList(request);
        }
        
        public PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcList_Output EDC_spcGet_spcSR_spcList(PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcList_Input EDC_spcGet_spcSR_spcList_Input) {
            PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListRequest inValue = new PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListRequest();
            inValue.EDC_spcGet_spcSR_spcList_Input = EDC_spcGet_spcSR_spcList_Input;
            PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListResponse retVal = ((PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcContact_spcSR_spcWF)(this)).EDC_spcGet_spcSR_spcList(inValue);
            return retVal.EDC_spcGet_spcSR_spcList_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListResponse> PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcContact_spcSR_spcWF.EDC_spcGet_spcSR_spcListAsync(PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListRequest request) {
            return base.Channel.EDC_spcGet_spcSR_spcListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListResponse> EDC_spcGet_spcSR_spcListAsync(PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcList_Input EDC_spcGet_spcSR_spcList_Input) {
            PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListRequest inValue = new PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcSR_spcListRequest();
            inValue.EDC_spcGet_spcSR_spcList_Input = EDC_spcGet_spcSR_spcList_Input;
            return ((PLEXEDC.WEB.UI.SiebelReferenceRequestGet.EDC_spcGet_spcContact_spcSR_spcWF)(this)).EDC_spcGet_spcSR_spcListAsync(inValue);
        }
    }
}
