//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLEXEDC.WEB.UI.SiebelReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReference.CreateServiceRequest")]
    public interface CreateServiceRequest {
        
        // CODEGEN: Generating message contract since the operation CreateSR is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:CreateSR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.UI.SiebelReference.CreateSRResponse CreateSR(PLEXEDC.WEB.UI.SiebelReference.CreateSRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:CreateSR", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.CreateSRResponse> CreateSRAsync(PLEXEDC.WEB.UI.SiebelReference.CreateSRRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class CreateSR_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string subAreaField;
        
        private string areaField;
        
        private string customerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubArea {
            get {
                return this.subAreaField;
            }
            set {
                this.subAreaField = value;
                this.RaisePropertyChanged("SubArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/PLX%20Service%20Request")]
    public partial class ServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaField;
        
        private string contactIdField;
        
        private string iNSProductField;
        
        private string statusField;
        
        private string subAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
                this.RaisePropertyChanged("ContactId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string INSProduct {
            get {
                return this.iNSProductField;
            }
            set {
                this.iNSProductField = value;
                this.RaisePropertyChanged("INSProduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sub-Area", Order=4)]
        public string SubArea {
            get {
                return this.subAreaField;
            }
            set {
                this.subAreaField = value;
                this.RaisePropertyChanged("SubArea");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/PLX%20Activities")]
    public partial class Action : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string activitySRIdField;
        
        private string descriptionField;
        
        private string statusField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ActivitySRId {
            get {
                return this.activitySRIdField;
            }
            set {
                this.activitySRIdField = value;
                this.RaisePropertyChanged("ActivitySRId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class CreateSR_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string serviceRequestNumberField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServiceRequestNumber {
            get {
                return this.serviceRequestNumberField;
            }
            set {
                this.serviceRequestNumberField = value;
                this.RaisePropertyChanged("ServiceRequestNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.CreateSR_Input CreateSR_Input;
        
        public CreateSRRequest() {
        }
        
        public CreateSRRequest(PLEXEDC.WEB.UI.SiebelReference.CreateSR_Input CreateSR_Input) {
            this.CreateSR_Input = CreateSR_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.CreateSR_Output CreateSR_Output;
        
        public CreateSRResponse() {
        }
        
        public CreateSRResponse(PLEXEDC.WEB.UI.SiebelReference.CreateSR_Output CreateSR_Output) {
            this.CreateSR_Output = CreateSR_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreateServiceRequestChannel : PLEXEDC.WEB.UI.SiebelReference.CreateServiceRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateServiceRequestClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.UI.SiebelReference.CreateServiceRequest>, PLEXEDC.WEB.UI.SiebelReference.CreateServiceRequest {
        
        public CreateServiceRequestClient() {
        }
        
        public CreateServiceRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateServiceRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateServiceRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateServiceRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.UI.SiebelReference.CreateSRResponse PLEXEDC.WEB.UI.SiebelReference.CreateServiceRequest.CreateSR(PLEXEDC.WEB.UI.SiebelReference.CreateSRRequest request) {
            return base.Channel.CreateSR(request);
        }
        
        public PLEXEDC.WEB.UI.SiebelReference.CreateSR_Output CreateSR(PLEXEDC.WEB.UI.SiebelReference.CreateSR_Input CreateSR_Input) {
            PLEXEDC.WEB.UI.SiebelReference.CreateSRRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.CreateSRRequest();
            inValue.CreateSR_Input = CreateSR_Input;
            PLEXEDC.WEB.UI.SiebelReference.CreateSRResponse retVal = ((PLEXEDC.WEB.UI.SiebelReference.CreateServiceRequest)(this)).CreateSR(inValue);
            return retVal.CreateSR_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.CreateSRResponse> PLEXEDC.WEB.UI.SiebelReference.CreateServiceRequest.CreateSRAsync(PLEXEDC.WEB.UI.SiebelReference.CreateSRRequest request) {
            return base.Channel.CreateSRAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.CreateSRResponse> CreateSRAsync(PLEXEDC.WEB.UI.SiebelReference.CreateSR_Input CreateSR_Input) {
            PLEXEDC.WEB.UI.SiebelReference.CreateSRRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.CreateSRRequest();
            inValue.CreateSR_Input = CreateSR_Input;
            return ((PLEXEDC.WEB.UI.SiebelReference.CreateServiceRequest)(this)).CreateSRAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReference.GetServiceRequest")]
    public interface GetServiceRequest {
        
        // CODEGEN: Generating message contract since the operation GetSRCount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:GetSRCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.UI.SiebelReference.GetSRCountResponse GetSRCount(PLEXEDC.WEB.UI.SiebelReference.GetSRCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:GetSRCount", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.GetSRCountResponse> GetSRCountAsync(PLEXEDC.WEB.UI.SiebelReference.GetSRCountRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class GetSRCount_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class GetSRCount_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string serviceRequestCountField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServiceRequestCount {
            get {
                return this.serviceRequestCountField;
            }
            set {
                this.serviceRequestCountField = value;
                this.RaisePropertyChanged("ServiceRequestCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSRCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.GetSRCount_Input GetSRCount_Input;
        
        public GetSRCountRequest() {
        }
        
        public GetSRCountRequest(PLEXEDC.WEB.UI.SiebelReference.GetSRCount_Input GetSRCount_Input) {
            this.GetSRCount_Input = GetSRCount_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSRCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.GetSRCount_Output GetSRCount_Output;
        
        public GetSRCountResponse() {
        }
        
        public GetSRCountResponse(PLEXEDC.WEB.UI.SiebelReference.GetSRCount_Output GetSRCount_Output) {
            this.GetSRCount_Output = GetSRCount_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetServiceRequestChannel : PLEXEDC.WEB.UI.SiebelReference.GetServiceRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetServiceRequestClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.UI.SiebelReference.GetServiceRequest>, PLEXEDC.WEB.UI.SiebelReference.GetServiceRequest {
        
        public GetServiceRequestClient() {
        }
        
        public GetServiceRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetServiceRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetServiceRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetServiceRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.UI.SiebelReference.GetSRCountResponse PLEXEDC.WEB.UI.SiebelReference.GetServiceRequest.GetSRCount(PLEXEDC.WEB.UI.SiebelReference.GetSRCountRequest request) {
            return base.Channel.GetSRCount(request);
        }
        
        public PLEXEDC.WEB.UI.SiebelReference.GetSRCount_Output GetSRCount(PLEXEDC.WEB.UI.SiebelReference.GetSRCount_Input GetSRCount_Input) {
            PLEXEDC.WEB.UI.SiebelReference.GetSRCountRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.GetSRCountRequest();
            inValue.GetSRCount_Input = GetSRCount_Input;
            PLEXEDC.WEB.UI.SiebelReference.GetSRCountResponse retVal = ((PLEXEDC.WEB.UI.SiebelReference.GetServiceRequest)(this)).GetSRCount(inValue);
            return retVal.GetSRCount_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.GetSRCountResponse> PLEXEDC.WEB.UI.SiebelReference.GetServiceRequest.GetSRCountAsync(PLEXEDC.WEB.UI.SiebelReference.GetSRCountRequest request) {
            return base.Channel.GetSRCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.GetSRCountResponse> GetSRCountAsync(PLEXEDC.WEB.UI.SiebelReference.GetSRCount_Input GetSRCount_Input) {
            PLEXEDC.WEB.UI.SiebelReference.GetSRCountRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.GetSRCountRequest();
            inValue.GetSRCount_Input = GetSRCount_Input;
            return ((PLEXEDC.WEB.UI.SiebelReference.GetServiceRequest)(this)).GetSRCountAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReference.GetSRActivities")]
    public interface GetSRActivities {
        
        // CODEGEN: Generating message contract since the operation GetSRActivities is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:GetSRActivities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesResponse GetSRActivities(PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:GetSRActivities", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesResponse> GetSRActivitiesAsync(PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class GetSRActivities_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceRequestNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceRequestNumber {
            get {
                return this.serviceRequestNumberField;
            }
            set {
                this.serviceRequestNumberField = value;
                this.RaisePropertyChanged("ServiceRequestNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class GetSRActivities_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private Action[] listOfPlxActivitiesField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/PLX%20Activities", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Action[] ListOfPlxActivities {
            get {
                return this.listOfPlxActivitiesField;
            }
            set {
                this.listOfPlxActivitiesField = value;
                this.RaisePropertyChanged("ListOfPlxActivities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSRActivitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.GetSRActivities_Input GetSRActivities_Input;
        
        public GetSRActivitiesRequest() {
        }
        
        public GetSRActivitiesRequest(PLEXEDC.WEB.UI.SiebelReference.GetSRActivities_Input GetSRActivities_Input) {
            this.GetSRActivities_Input = GetSRActivities_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSRActivitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.GetSRActivities_Output GetSRActivities_Output;
        
        public GetSRActivitiesResponse() {
        }
        
        public GetSRActivitiesResponse(PLEXEDC.WEB.UI.SiebelReference.GetSRActivities_Output GetSRActivities_Output) {
            this.GetSRActivities_Output = GetSRActivities_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetSRActivitiesChannel : PLEXEDC.WEB.UI.SiebelReference.GetSRActivities, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSRActivitiesClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.UI.SiebelReference.GetSRActivities>, PLEXEDC.WEB.UI.SiebelReference.GetSRActivities {
        
        public GetSRActivitiesClient() {
        }
        
        public GetSRActivitiesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetSRActivitiesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSRActivitiesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSRActivitiesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesResponse PLEXEDC.WEB.UI.SiebelReference.GetSRActivities.GetSRActivities(PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesRequest request) {
            return base.Channel.GetSRActivities(request);
        }
        
        public PLEXEDC.WEB.UI.SiebelReference.GetSRActivities_Output GetSRActivities(PLEXEDC.WEB.UI.SiebelReference.GetSRActivities_Input GetSRActivities_Input) {
            PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesRequest();
            inValue.GetSRActivities_Input = GetSRActivities_Input;
            PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesResponse retVal = ((PLEXEDC.WEB.UI.SiebelReference.GetSRActivities)(this)).GetSRActivities(inValue);
            return retVal.GetSRActivities_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesResponse> PLEXEDC.WEB.UI.SiebelReference.GetSRActivities.GetSRActivitiesAsync(PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesRequest request) {
            return base.Channel.GetSRActivitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesResponse> GetSRActivitiesAsync(PLEXEDC.WEB.UI.SiebelReference.GetSRActivities_Input GetSRActivities_Input) {
            PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.GetSRActivitiesRequest();
            inValue.GetSRActivities_Input = GetSRActivities_Input;
            return ((PLEXEDC.WEB.UI.SiebelReference.GetSRActivities)(this)).GetSRActivitiesAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReference.UpdateServiceRequest")]
    public interface UpdateServiceRequest {
        
        // CODEGEN: Generating message contract since the operation UpdateSR is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:UpdateSR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.UI.SiebelReference.UpdateSRResponse UpdateSR(PLEXEDC.WEB.UI.SiebelReference.UpdateSRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:UpdateSR", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.UpdateSRResponse> UpdateSRAsync(PLEXEDC.WEB.UI.SiebelReference.UpdateSRRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class UpdateSR_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceRequestStatusField;
        
        private string serviceRequestNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceRequestStatus {
            get {
                return this.serviceRequestStatusField;
            }
            set {
                this.serviceRequestStatusField = value;
                this.RaisePropertyChanged("ServiceRequestStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceRequestNumber {
            get {
                return this.serviceRequestNumberField;
            }
            set {
                this.serviceRequestNumberField = value;
                this.RaisePropertyChanged("ServiceRequestNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class UpdateSR_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.UpdateSR_Input UpdateSR_Input;
        
        public UpdateSRRequest() {
        }
        
        public UpdateSRRequest(PLEXEDC.WEB.UI.SiebelReference.UpdateSR_Input UpdateSR_Input) {
            this.UpdateSR_Input = UpdateSR_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.UpdateSR_Output UpdateSR_Output;
        
        public UpdateSRResponse() {
        }
        
        public UpdateSRResponse(PLEXEDC.WEB.UI.SiebelReference.UpdateSR_Output UpdateSR_Output) {
            this.UpdateSR_Output = UpdateSR_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdateServiceRequestChannel : PLEXEDC.WEB.UI.SiebelReference.UpdateServiceRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateServiceRequestClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.UI.SiebelReference.UpdateServiceRequest>, PLEXEDC.WEB.UI.SiebelReference.UpdateServiceRequest {
        
        public UpdateServiceRequestClient() {
        }
        
        public UpdateServiceRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateServiceRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateServiceRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateServiceRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.UI.SiebelReference.UpdateSRResponse PLEXEDC.WEB.UI.SiebelReference.UpdateServiceRequest.UpdateSR(PLEXEDC.WEB.UI.SiebelReference.UpdateSRRequest request) {
            return base.Channel.UpdateSR(request);
        }
        
        public PLEXEDC.WEB.UI.SiebelReference.UpdateSR_Output UpdateSR(PLEXEDC.WEB.UI.SiebelReference.UpdateSR_Input UpdateSR_Input) {
            PLEXEDC.WEB.UI.SiebelReference.UpdateSRRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.UpdateSRRequest();
            inValue.UpdateSR_Input = UpdateSR_Input;
            PLEXEDC.WEB.UI.SiebelReference.UpdateSRResponse retVal = ((PLEXEDC.WEB.UI.SiebelReference.UpdateServiceRequest)(this)).UpdateSR(inValue);
            return retVal.UpdateSR_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.UpdateSRResponse> PLEXEDC.WEB.UI.SiebelReference.UpdateServiceRequest.UpdateSRAsync(PLEXEDC.WEB.UI.SiebelReference.UpdateSRRequest request) {
            return base.Channel.UpdateSRAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.UpdateSRResponse> UpdateSRAsync(PLEXEDC.WEB.UI.SiebelReference.UpdateSR_Input UpdateSR_Input) {
            PLEXEDC.WEB.UI.SiebelReference.UpdateSRRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.UpdateSRRequest();
            inValue.UpdateSR_Input = UpdateSR_Input;
            return ((PLEXEDC.WEB.UI.SiebelReference.UpdateServiceRequest)(this)).UpdateSRAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReference.GetCustServiceRequests")]
    public interface GetCustServiceRequests {
        
        // CODEGEN: Generating message contract since the operation GetCustomersSRs is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:GetCustomersSRs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsResponse GetCustomersSRs(PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:GetCustomersSRs", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsResponse> GetCustomersSRsAsync(PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class GetCustomersSRs_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class GetCustomersSRs_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceRequest[] listOfPlxServiceRequestField;
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/PLX%20Service%20Request", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceRequest[] ListOfPlxServiceRequest {
            get {
                return this.listOfPlxServiceRequestField;
            }
            set {
                this.listOfPlxServiceRequestField = value;
                this.RaisePropertyChanged("ListOfPlxServiceRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersSRsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRs_Input GetCustomersSRs_Input;
        
        public GetCustomersSRsRequest() {
        }
        
        public GetCustomersSRsRequest(PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRs_Input GetCustomersSRs_Input) {
            this.GetCustomersSRs_Input = GetCustomersSRs_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersSRsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRs_Output GetCustomersSRs_Output;
        
        public GetCustomersSRsResponse() {
        }
        
        public GetCustomersSRsResponse(PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRs_Output GetCustomersSRs_Output) {
            this.GetCustomersSRs_Output = GetCustomersSRs_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetCustServiceRequestsChannel : PLEXEDC.WEB.UI.SiebelReference.GetCustServiceRequests, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustServiceRequestsClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.UI.SiebelReference.GetCustServiceRequests>, PLEXEDC.WEB.UI.SiebelReference.GetCustServiceRequests {
        
        public GetCustServiceRequestsClient() {
        }
        
        public GetCustServiceRequestsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetCustServiceRequestsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCustServiceRequestsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCustServiceRequestsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsResponse PLEXEDC.WEB.UI.SiebelReference.GetCustServiceRequests.GetCustomersSRs(PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsRequest request) {
            return base.Channel.GetCustomersSRs(request);
        }
        
        public PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRs_Output GetCustomersSRs(PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRs_Input GetCustomersSRs_Input) {
            PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsRequest();
            inValue.GetCustomersSRs_Input = GetCustomersSRs_Input;
            PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsResponse retVal = ((PLEXEDC.WEB.UI.SiebelReference.GetCustServiceRequests)(this)).GetCustomersSRs(inValue);
            return retVal.GetCustomersSRs_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsResponse> PLEXEDC.WEB.UI.SiebelReference.GetCustServiceRequests.GetCustomersSRsAsync(PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsRequest request) {
            return base.Channel.GetCustomersSRsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsResponse> GetCustomersSRsAsync(PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRs_Input GetCustomersSRs_Input) {
            PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.GetCustomersSRsRequest();
            inValue.GetCustomersSRs_Input = GetCustomersSRs_Input;
            return ((PLEXEDC.WEB.UI.SiebelReference.GetCustServiceRequests)(this)).GetCustomersSRsAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReference.QueryServiceRequest")]
    public interface QueryServiceRequest {
        
        // CODEGEN: Generating message contract since the operation QuerySR is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:QuerySR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.UI.SiebelReference.QuerySRResponse QuerySR(PLEXEDC.WEB.UI.SiebelReference.QuerySRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:QuerySR", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.QuerySRResponse> QuerySRAsync(PLEXEDC.WEB.UI.SiebelReference.QuerySRRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class QuerySR_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceRequestNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceRequestNumber {
            get {
                return this.serviceRequestNumberField;
            }
            set {
                this.serviceRequestNumberField = value;
                this.RaisePropertyChanged("ServiceRequestNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class QuerySR_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaField;
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string serviceRequestStatusField;
        
        private string statusField;
        
        private string subAreaField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceRequestStatus {
            get {
                return this.serviceRequestStatusField;
            }
            set {
                this.serviceRequestStatusField = value;
                this.RaisePropertyChanged("ServiceRequestStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SubArea {
            get {
                return this.subAreaField;
            }
            set {
                this.subAreaField = value;
                this.RaisePropertyChanged("SubArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuerySRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.QuerySR_Input QuerySR_Input;
        
        public QuerySRRequest() {
        }
        
        public QuerySRRequest(PLEXEDC.WEB.UI.SiebelReference.QuerySR_Input QuerySR_Input) {
            this.QuerySR_Input = QuerySR_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuerySRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.UI.SiebelReference.QuerySR_Output QuerySR_Output;
        
        public QuerySRResponse() {
        }
        
        public QuerySRResponse(PLEXEDC.WEB.UI.SiebelReference.QuerySR_Output QuerySR_Output) {
            this.QuerySR_Output = QuerySR_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryServiceRequestChannel : PLEXEDC.WEB.UI.SiebelReference.QueryServiceRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryServiceRequestClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.UI.SiebelReference.QueryServiceRequest>, PLEXEDC.WEB.UI.SiebelReference.QueryServiceRequest {
        
        public QueryServiceRequestClient() {
        }
        
        public QueryServiceRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryServiceRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.UI.SiebelReference.QuerySRResponse PLEXEDC.WEB.UI.SiebelReference.QueryServiceRequest.QuerySR(PLEXEDC.WEB.UI.SiebelReference.QuerySRRequest request) {
            return base.Channel.QuerySR(request);
        }
        
        public PLEXEDC.WEB.UI.SiebelReference.QuerySR_Output QuerySR(PLEXEDC.WEB.UI.SiebelReference.QuerySR_Input QuerySR_Input) {
            PLEXEDC.WEB.UI.SiebelReference.QuerySRRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.QuerySRRequest();
            inValue.QuerySR_Input = QuerySR_Input;
            PLEXEDC.WEB.UI.SiebelReference.QuerySRResponse retVal = ((PLEXEDC.WEB.UI.SiebelReference.QueryServiceRequest)(this)).QuerySR(inValue);
            return retVal.QuerySR_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.QuerySRResponse> PLEXEDC.WEB.UI.SiebelReference.QueryServiceRequest.QuerySRAsync(PLEXEDC.WEB.UI.SiebelReference.QuerySRRequest request) {
            return base.Channel.QuerySRAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.UI.SiebelReference.QuerySRResponse> QuerySRAsync(PLEXEDC.WEB.UI.SiebelReference.QuerySR_Input QuerySR_Input) {
            PLEXEDC.WEB.UI.SiebelReference.QuerySRRequest inValue = new PLEXEDC.WEB.UI.SiebelReference.QuerySRRequest();
            inValue.QuerySR_Input = QuerySR_Input;
            return ((PLEXEDC.WEB.UI.SiebelReference.QueryServiceRequest)(this)).QuerySRAsync(inValue);
        }
    }
}
