//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLEXEDC.WEB.BAL.SiebelReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReference.EDC_spcSR_spcDetails")]
    public interface EDC_spcSR_spcDetails {
        
        // CODEGEN: Generating message contract since the operation EDC_spcSR_spcDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:EDC_spcSR_spcDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsResponse EDC_spcSR_spcDetails(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:EDC_spcSR_spcDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsResponse> EDC_spcSR_spcDetailsAsync(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class EDC_spcSR_spcDetails_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/XMLP%20Account")]
    public partial class Activity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string statusField;
        
        private string priorityField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ServiceRequest", Namespace="http://www.siebel.com/xml/XMLP%20Account")]
    public partial class ServiceRequest1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sRNumberField;
        
        private Activity[] listOf_ActivityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SRNumber {
            get {
                return this.sRNumberField;
            }
            set {
                this.sRNumberField = value;
                this.RaisePropertyChanged("SRNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Activity[] ListOf_Activity {
            get {
                return this.listOf_ActivityField;
            }
            set {
                this.listOf_ActivityField = value;
                this.RaisePropertyChanged("ListOf_Activity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/HDK%20Service%20Request")]
    public partial class ServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sRNumberField;
        
        private string typeField;
        
        private string areaField;
        
        private string subAreaField;
        
        private string statusField;
        
        private string subStatusField;
        
        private string priorityField;
        
        private string summaryField;
        
        private string closureCommentsField;
        
        private string citizenIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SRNumber {
            get {
                return this.sRNumberField;
            }
            set {
                this.sRNumberField = value;
                this.RaisePropertyChanged("SRNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SubArea {
            get {
                return this.subAreaField;
            }
            set {
                this.subAreaField = value;
                this.RaisePropertyChanged("SubArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SubStatus {
            get {
                return this.subStatusField;
            }
            set {
                this.subStatusField = value;
                this.RaisePropertyChanged("SubStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("Summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ClosureComments {
            get {
                return this.closureCommentsField;
            }
            set {
                this.closureCommentsField = value;
                this.RaisePropertyChanged("ClosureComments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CitizenId {
            get {
                return this.citizenIdField;
            }
            set {
                this.citizenIdField = value;
                this.RaisePropertyChanged("CitizenId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class EDC_spcSR_spcDetails_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceRequest[] listOf_ServiceRequestField;
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/HDK%20Service%20Request", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceRequest[] ListOf_ServiceRequest {
            get {
                return this.listOf_ServiceRequestField;
            }
            set {
                this.listOf_ServiceRequestField = value;
                this.RaisePropertyChanged("ListOf_ServiceRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EDC_spcSR_spcDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails_Input EDC_spcSR_spcDetails_Input;
        
        public EDC_spcSR_spcDetailsRequest() {
        }
        
        public EDC_spcSR_spcDetailsRequest(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails_Input EDC_spcSR_spcDetails_Input) {
            this.EDC_spcSR_spcDetails_Input = EDC_spcSR_spcDetails_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EDC_spcSR_spcDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails_Output EDC_spcSR_spcDetails_Output;
        
        public EDC_spcSR_spcDetailsResponse() {
        }
        
        public EDC_spcSR_spcDetailsResponse(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails_Output EDC_spcSR_spcDetails_Output) {
            this.EDC_spcSR_spcDetails_Output = EDC_spcSR_spcDetails_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EDC_spcSR_spcDetailsChannel : PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDC_spcSR_spcDetailsClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails>, PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails {
        
        public EDC_spcSR_spcDetailsClient() {
        }
        
        public EDC_spcSR_spcDetailsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDC_spcSR_spcDetailsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcSR_spcDetailsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcSR_spcDetailsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsResponse PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails.EDC_spcSR_spcDetails(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsRequest request) {
            return base.Channel.EDC_spcSR_spcDetails(request);
        }
        
        public PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails_Output EDC_spcSR_spcDetails(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails_Input EDC_spcSR_spcDetails_Input) {
            PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsRequest inValue = new PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsRequest();
            inValue.EDC_spcSR_spcDetails_Input = EDC_spcSR_spcDetails_Input;
            PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsResponse retVal = ((PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails)(this)).EDC_spcSR_spcDetails(inValue);
            return retVal.EDC_spcSR_spcDetails_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsResponse> PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails.EDC_spcSR_spcDetailsAsync(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsRequest request) {
            return base.Channel.EDC_spcSR_spcDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsResponse> EDC_spcSR_spcDetailsAsync(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails_Input EDC_spcSR_spcDetails_Input) {
            PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsRequest inValue = new PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetailsRequest();
            inValue.EDC_spcSR_spcDetails_Input = EDC_spcSR_spcDetails_Input;
            return ((PLEXEDC.WEB.BAL.SiebelReference.EDC_spcSR_spcDetails)(this)).EDC_spcSR_spcDetailsAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReference.EDC_spcUpdate_spcSR")]
    public interface EDC_spcUpdate_spcSR {
        
        // CODEGEN: Generating message contract since the operation Update_spcSR is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:Update_spcSR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRResponse Update_spcSR(PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:Update_spcSR", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRResponse> Update_spcSRAsync(PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class Update_spcSR_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rootCauseField;
        
        private string summaryField;
        
        private string closureCommentsField;
        
        private string serviceRequestStatusField;
        
        private string serviceRequestNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RootCause {
            get {
                return this.rootCauseField;
            }
            set {
                this.rootCauseField = value;
                this.RaisePropertyChanged("RootCause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("Summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClosureComments {
            get {
                return this.closureCommentsField;
            }
            set {
                this.closureCommentsField = value;
                this.RaisePropertyChanged("ClosureComments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceRequestStatus {
            get {
                return this.serviceRequestStatusField;
            }
            set {
                this.serviceRequestStatusField = value;
                this.RaisePropertyChanged("ServiceRequestStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ServiceRequestNumber {
            get {
                return this.serviceRequestNumberField;
            }
            set {
                this.serviceRequestNumberField = value;
                this.RaisePropertyChanged("ServiceRequestNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class Update_spcSR_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_spcSRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.BAL.SiebelReference.Update_spcSR_Input Update_spcSR_Input;
        
        public Update_spcSRRequest() {
        }
        
        public Update_spcSRRequest(PLEXEDC.WEB.BAL.SiebelReference.Update_spcSR_Input Update_spcSR_Input) {
            this.Update_spcSR_Input = Update_spcSR_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_spcSRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.BAL.SiebelReference.Update_spcSR_Output Update_spcSR_Output;
        
        public Update_spcSRResponse() {
        }
        
        public Update_spcSRResponse(PLEXEDC.WEB.BAL.SiebelReference.Update_spcSR_Output Update_spcSR_Output) {
            this.Update_spcSR_Output = Update_spcSR_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EDC_spcUpdate_spcSRChannel : PLEXEDC.WEB.BAL.SiebelReference.EDC_spcUpdate_spcSR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDC_spcUpdate_spcSRClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.BAL.SiebelReference.EDC_spcUpdate_spcSR>, PLEXEDC.WEB.BAL.SiebelReference.EDC_spcUpdate_spcSR {
        
        public EDC_spcUpdate_spcSRClient() {
        }
        
        public EDC_spcUpdate_spcSRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDC_spcUpdate_spcSRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcUpdate_spcSRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcUpdate_spcSRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRResponse PLEXEDC.WEB.BAL.SiebelReference.EDC_spcUpdate_spcSR.Update_spcSR(PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRRequest request) {
            return base.Channel.Update_spcSR(request);
        }
        
        public PLEXEDC.WEB.BAL.SiebelReference.Update_spcSR_Output Update_spcSR(PLEXEDC.WEB.BAL.SiebelReference.Update_spcSR_Input Update_spcSR_Input) {
            PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRRequest inValue = new PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRRequest();
            inValue.Update_spcSR_Input = Update_spcSR_Input;
            PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRResponse retVal = ((PLEXEDC.WEB.BAL.SiebelReference.EDC_spcUpdate_spcSR)(this)).Update_spcSR(inValue);
            return retVal.Update_spcSR_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRResponse> PLEXEDC.WEB.BAL.SiebelReference.EDC_spcUpdate_spcSR.Update_spcSRAsync(PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRRequest request) {
            return base.Channel.Update_spcSRAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRResponse> Update_spcSRAsync(PLEXEDC.WEB.BAL.SiebelReference.Update_spcSR_Input Update_spcSR_Input) {
            PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRRequest inValue = new PLEXEDC.WEB.BAL.SiebelReference.Update_spcSRRequest();
            inValue.Update_spcSR_Input = Update_spcSR_Input;
            return ((PLEXEDC.WEB.BAL.SiebelReference.EDC_spcUpdate_spcSR)(this)).Update_spcSRAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReference.EDC_spcQuery_spcSR")]
    public interface EDC_spcQuery_spcSR {
        
        // CODEGEN: Generating message contract since the operation Query_spcSR is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:Query_spcSR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRResponse Query_spcSR(PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:Query_spcSR", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRResponse> Query_spcSRAsync(PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class Query_spcSR_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sRNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SRNumber {
            get {
                return this.sRNumberField;
            }
            set {
                this.sRNumberField = value;
                this.RaisePropertyChanged("SRNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class Query_spcSR_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string sRStatusField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SRStatus {
            get {
                return this.sRStatusField;
            }
            set {
                this.sRStatusField = value;
                this.RaisePropertyChanged("SRStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Query_spcSRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.BAL.SiebelReference.Query_spcSR_Input Query_spcSR_Input;
        
        public Query_spcSRRequest() {
        }
        
        public Query_spcSRRequest(PLEXEDC.WEB.BAL.SiebelReference.Query_spcSR_Input Query_spcSR_Input) {
            this.Query_spcSR_Input = Query_spcSR_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Query_spcSRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.BAL.SiebelReference.Query_spcSR_Output Query_spcSR_Output;
        
        public Query_spcSRResponse() {
        }
        
        public Query_spcSRResponse(PLEXEDC.WEB.BAL.SiebelReference.Query_spcSR_Output Query_spcSR_Output) {
            this.Query_spcSR_Output = Query_spcSR_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EDC_spcQuery_spcSRChannel : PLEXEDC.WEB.BAL.SiebelReference.EDC_spcQuery_spcSR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDC_spcQuery_spcSRClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.BAL.SiebelReference.EDC_spcQuery_spcSR>, PLEXEDC.WEB.BAL.SiebelReference.EDC_spcQuery_spcSR {
        
        public EDC_spcQuery_spcSRClient() {
        }
        
        public EDC_spcQuery_spcSRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDC_spcQuery_spcSRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcQuery_spcSRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcQuery_spcSRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRResponse PLEXEDC.WEB.BAL.SiebelReference.EDC_spcQuery_spcSR.Query_spcSR(PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRRequest request) {
            return base.Channel.Query_spcSR(request);
        }
        
        public PLEXEDC.WEB.BAL.SiebelReference.Query_spcSR_Output Query_spcSR(PLEXEDC.WEB.BAL.SiebelReference.Query_spcSR_Input Query_spcSR_Input) {
            PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRRequest inValue = new PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRRequest();
            inValue.Query_spcSR_Input = Query_spcSR_Input;
            PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRResponse retVal = ((PLEXEDC.WEB.BAL.SiebelReference.EDC_spcQuery_spcSR)(this)).Query_spcSR(inValue);
            return retVal.Query_spcSR_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRResponse> PLEXEDC.WEB.BAL.SiebelReference.EDC_spcQuery_spcSR.Query_spcSRAsync(PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRRequest request) {
            return base.Channel.Query_spcSRAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRResponse> Query_spcSRAsync(PLEXEDC.WEB.BAL.SiebelReference.Query_spcSR_Input Query_spcSR_Input) {
            PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRRequest inValue = new PLEXEDC.WEB.BAL.SiebelReference.Query_spcSRRequest();
            inValue.Query_spcSR_Input = Query_spcSR_Input;
            return ((PLEXEDC.WEB.BAL.SiebelReference.EDC_spcQuery_spcSR)(this)).Query_spcSRAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReference.EDC_spcContact_spcGet_spcSR_spcActivity_spcWF")]
    public interface EDC_spcContact_spcGet_spcSR_spcActivity_spcWF {
        
        // CODEGEN: Generating message contract since the operation EDC_spcGet_spcSR_spcActivities is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:EDC_spcGet_spcSR_spcActivities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesResponse EDC_spcGet_spcSR_spcActivities(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:EDC_spcGet_spcSR_spcActivities", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesResponse> EDC_spcGet_spcSR_spcActivitiesAsync(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class EDC_spcGet_spcSR_spcActivities_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceRequestNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceRequestNumber {
            get {
                return this.serviceRequestNumberField;
            }
            set {
                this.serviceRequestNumberField = value;
                this.RaisePropertyChanged("ServiceRequestNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class EDC_spcGet_spcSR_spcActivities_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceRequest1[] listOf_ServiceRequestField;
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/XMLP%20Account", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceRequest1[] ListOf_ServiceRequest {
            get {
                return this.listOf_ServiceRequestField;
            }
            set {
                this.listOf_ServiceRequestField = value;
                this.RaisePropertyChanged("ListOf_ServiceRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EDC_spcGet_spcSR_spcActivitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivities_Input EDC_spcGet_spcSR_spcActivities_Input;
        
        public EDC_spcGet_spcSR_spcActivitiesRequest() {
        }
        
        public EDC_spcGet_spcSR_spcActivitiesRequest(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivities_Input EDC_spcGet_spcSR_spcActivities_Input) {
            this.EDC_spcGet_spcSR_spcActivities_Input = EDC_spcGet_spcSR_spcActivities_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EDC_spcGet_spcSR_spcActivitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivities_Output EDC_spcGet_spcSR_spcActivities_Output;
        
        public EDC_spcGet_spcSR_spcActivitiesResponse() {
        }
        
        public EDC_spcGet_spcSR_spcActivitiesResponse(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivities_Output EDC_spcGet_spcSR_spcActivities_Output) {
            this.EDC_spcGet_spcSR_spcActivities_Output = EDC_spcGet_spcSR_spcActivities_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EDC_spcContact_spcGet_spcSR_spcActivity_spcWFChannel : PLEXEDC.WEB.BAL.SiebelReference.EDC_spcContact_spcGet_spcSR_spcActivity_spcWF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDC_spcContact_spcGet_spcSR_spcActivity_spcWFClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.BAL.SiebelReference.EDC_spcContact_spcGet_spcSR_spcActivity_spcWF>, PLEXEDC.WEB.BAL.SiebelReference.EDC_spcContact_spcGet_spcSR_spcActivity_spcWF {
        
        public EDC_spcContact_spcGet_spcSR_spcActivity_spcWFClient() {
        }
        
        public EDC_spcContact_spcGet_spcSR_spcActivity_spcWFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDC_spcContact_spcGet_spcSR_spcActivity_spcWFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcContact_spcGet_spcSR_spcActivity_spcWFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcContact_spcGet_spcSR_spcActivity_spcWFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesResponse PLEXEDC.WEB.BAL.SiebelReference.EDC_spcContact_spcGet_spcSR_spcActivity_spcWF.EDC_spcGet_spcSR_spcActivities(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesRequest request) {
            return base.Channel.EDC_spcGet_spcSR_spcActivities(request);
        }
        
        public PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivities_Output EDC_spcGet_spcSR_spcActivities(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivities_Input EDC_spcGet_spcSR_spcActivities_Input) {
            PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesRequest inValue = new PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesRequest();
            inValue.EDC_spcGet_spcSR_spcActivities_Input = EDC_spcGet_spcSR_spcActivities_Input;
            PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesResponse retVal = ((PLEXEDC.WEB.BAL.SiebelReference.EDC_spcContact_spcGet_spcSR_spcActivity_spcWF)(this)).EDC_spcGet_spcSR_spcActivities(inValue);
            return retVal.EDC_spcGet_spcSR_spcActivities_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesResponse> PLEXEDC.WEB.BAL.SiebelReference.EDC_spcContact_spcGet_spcSR_spcActivity_spcWF.EDC_spcGet_spcSR_spcActivitiesAsync(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesRequest request) {
            return base.Channel.EDC_spcGet_spcSR_spcActivitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesResponse> EDC_spcGet_spcSR_spcActivitiesAsync(PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivities_Input EDC_spcGet_spcSR_spcActivities_Input) {
            PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesRequest inValue = new PLEXEDC.WEB.BAL.SiebelReference.EDC_spcGet_spcSR_spcActivitiesRequest();
            inValue.EDC_spcGet_spcSR_spcActivities_Input = EDC_spcGet_spcSR_spcActivities_Input;
            return ((PLEXEDC.WEB.BAL.SiebelReference.EDC_spcContact_spcGet_spcSR_spcActivity_spcWF)(this)).EDC_spcGet_spcSR_spcActivitiesAsync(inValue);
        }
    }
}
