//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLEXEDC.WEB.BAL.SiebelReferenceCreate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="SiebelReferenceCreate.EDC_spcCreate_spcSR")]
    public interface EDC_spcCreate_spcSR {
        
        // CODEGEN: Generating message contract since the operation CreateSR is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:CreateSR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRResponse CreateSR(PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:CreateSR", ReplyAction="*")]
        System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRResponse> CreateSRAsync(PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class CreateSR_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerNumberField;
        
        private string abstractField;
        
        private string typeField;
        
        private string subAreaField;
        
        private string areaField;
        
        private string sourceField;
        
        private string priorityField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
                this.RaisePropertyChanged("Abstract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SubArea {
            get {
                return this.subAreaField;
            }
            set {
                this.subAreaField = value;
                this.RaisePropertyChanged("SubArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class CreateSR_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerNumberField;
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string object_spcIdField;
        
        private string sRIdField;
        
        private string sRNumberField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Object_spcId {
            get {
                return this.object_spcIdField;
            }
            set {
                this.object_spcIdField = value;
                this.RaisePropertyChanged("Object_spcId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SRId {
            get {
                return this.sRIdField;
            }
            set {
                this.sRIdField = value;
                this.RaisePropertyChanged("SRId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SRNumber {
            get {
                return this.sRNumberField;
            }
            set {
                this.sRNumberField = value;
                this.RaisePropertyChanged("SRNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSR_Input CreateSR_Input;
        
        public CreateSRRequest() {
        }
        
        public CreateSRRequest(PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSR_Input CreateSR_Input) {
            this.CreateSR_Input = CreateSR_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSR_Output CreateSR_Output;
        
        public CreateSRResponse() {
        }
        
        public CreateSRResponse(PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSR_Output CreateSR_Output) {
            this.CreateSR_Output = CreateSR_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EDC_spcCreate_spcSRChannel : PLEXEDC.WEB.BAL.SiebelReferenceCreate.EDC_spcCreate_spcSR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDC_spcCreate_spcSRClient : System.ServiceModel.ClientBase<PLEXEDC.WEB.BAL.SiebelReferenceCreate.EDC_spcCreate_spcSR>, PLEXEDC.WEB.BAL.SiebelReferenceCreate.EDC_spcCreate_spcSR {
        
        public EDC_spcCreate_spcSRClient() {
        }
        
        public EDC_spcCreate_spcSRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDC_spcCreate_spcSRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcCreate_spcSRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDC_spcCreate_spcSRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRResponse PLEXEDC.WEB.BAL.SiebelReferenceCreate.EDC_spcCreate_spcSR.CreateSR(PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRRequest request) {
            return base.Channel.CreateSR(request);
        }
        
        public PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSR_Output CreateSR(PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSR_Input CreateSR_Input) {
            PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRRequest inValue = new PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRRequest();
            inValue.CreateSR_Input = CreateSR_Input;
            PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRResponse retVal = ((PLEXEDC.WEB.BAL.SiebelReferenceCreate.EDC_spcCreate_spcSR)(this)).CreateSR(inValue);
            return retVal.CreateSR_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRResponse> PLEXEDC.WEB.BAL.SiebelReferenceCreate.EDC_spcCreate_spcSR.CreateSRAsync(PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRRequest request) {
            return base.Channel.CreateSRAsync(request);
        }
        
        public System.Threading.Tasks.Task<PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRResponse> CreateSRAsync(PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSR_Input CreateSR_Input) {
            PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRRequest inValue = new PLEXEDC.WEB.BAL.SiebelReferenceCreate.CreateSRRequest();
            inValue.CreateSR_Input = CreateSR_Input;
            return ((PLEXEDC.WEB.BAL.SiebelReferenceCreate.EDC_spcCreate_spcSR)(this)).CreateSRAsync(inValue);
        }
    }
}
